### ISSUE TITLE
Add EV3Dev Sound support

### ISSUE THREAD

**Issue by jabrena** [jabrena/ev3dev-lang-java#51]
https://github.com/ev3dev/ev3dev/wiki/Using-Sound

**Comment by jabrena** [comment]
Testing with C&C sounds:
https://www.reddit.com/r/commandandconquer/comments/13p3hc/audio_files_for_cc_original/
https://dl.dropboxusercontent.com/u/61712887/C%26CSounds.zip

@dlech nice feature!

**Comment by jabrena** [comment]
https://www.youtube.com/watch?v=7Uq92eCdNQM
http://www.bestoldgames.net/eng/old-games/command-and-conquer-gold.php
https://en.wikipedia.org/wiki/Command_%26_Conquer

**Comment by jabrena** [comment]
http://espeak.sourceforge.net/

**Comment by jabrena** [comment]
https://travesuras.wordpress.com/2012/01/11/20120111-1/

**Comment by jabrena** [comment]
Example using Spanish voice:

``` bash
espeak -ves --stdout "soy un robot bueno" | aplay
```

**Comment by jabrena** [comment]
``` bash
root@ev3dev:/home/cncsounds# aplay commando\ yes\ sir\!.wav 
Playing WAVE 'commando yes sir!.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
```

**Comment by jabrena** [comment]
http://www.campisabalos.es/files/quijote1.pdf

**Comment by jabrena** [comment]
``` bash
root@ev3dev:/home# espeak -ves -a 200 -s 200 -p 50  --stdout -f quijote.txt | aplay
```

**Comment by jabrena** [comment]
https://github.com/adityaravishankar/command-and-conquer/tree/master/audio/voice

**Comment by jabrena** [comment]
If I use this example:
http://stackoverflow.com/questions/6045384/playing-mp3-and-wav-in-java

``` java
	public static void playSound() {
	    try {
	    	File sound = new File("/home/cncsounds/commander.wav").getAbsoluteFile();
	        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(sound);
	        Clip clip = AudioSystem.getClip();
	        clip.open(audioInputStream);
	        clip.start();
	    } catch(Exception ex) {
	        System.out.println("Error with playing sound.");
	        ex.printStackTrace();
	    }
	}
```
I receive the following exception:

``` bash
Error with playing sound.
javax.sound.sampled.LineUnavailableException
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:714)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:283)
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:453)
	at ev3dev.examples.Test.playSound(Test.java:23)
	at ev3dev.examples.Test.main(Test.java:33)

```

**Comment by jabrena** [comment]
Using this way, is OK:

``` bash
    	String cmd = "aplay /home/cncsounds/commander.wav";
    	Shell.executeCommand(cmd);
```
