### ISSUE TITLE
Refactor Motors to use the parameter Address

### ISSUE THREAD

**Issue by jabrena** [jabrena/ev3dev-lang-java#68]
After every Kernel big change, it is necessary to reboot the EV3 Brick with EV3Dev to take effect this changes.

port_name has been removed to sysfs and the new property is address.
I have to refactor the class to avoid this error:

``` bash
root@ev3dev:/home# java -cp ev3-lang-java-0.2-SNAPSHOT.jar ev3dev.java.examples.Test
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: ev3dev.hardware.DeviceException: The device was not detected in: outA
	at ev3dev.hardware.EV3DevDevice.<init>(EV3DevDevice.java:19)
	at ev3dev.hardware.motor.BaseRegulatedMotor.<init>(BaseRegulatedMotor.java:68)
	at ev3dev.hardware.motor.EV3LargeRegulatedMotor.<init>(EV3LargeRegulatedMotor.java:22)
	at ev3dev.java.examples.Test.<clinit>(Test.java:15)
root@ev3dev:/home# java -cp ev3-lang-java-0.2-SNAPSHOT.jar ev3dev.java.examples.Test
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: ev3dev.hardware.DeviceException: The device was not detected in: outA
	at ev3dev.hardware.EV3DevDevice.<init>(EV3DevDevice.java:19)
	at ev3dev.hardware.motor.BaseRegulatedMotor.<init>(BaseRegulatedMotor.java:68)
	at ev3dev.hardware.motor.EV3LargeRegulatedMotor.<init>(EV3LargeRegulatedMotor.java:22)
	at ev3dev.java.examples.Test.<clinit>(Test.java:15)
root@ev3dev:/home# cd /sys/class/tacho-motor/
root@ev3dev:/sys/class/tacho-motor# ls
motor0  motor1
root@ev3dev:/sys/class/tacho-motor# cd motor0/
root@ev3dev:/sys/class/tacho-motor/motor0# ls
address        device         encoder_polarity  position_sp   speed             state          time_sp
command        driver_name    hold_pid          power         speed_pid         stop_command   uevent
commands       duty_cycle     polarity          ramp_down_sp  speed_regulation  stop_commands
count_per_rot  duty_cycle_sp  position          ramp_up_sp    speed_sp          subsystem
root@ev3dev:/sys/class/tacho-motor/motor0# cat address
outA
```

**Comment by jabrena** [comment]
Related issue:
https://github.com/jabrena/ev3dev-lang-java/issues/57

**Comment by jabrena** [comment]
Fixed problem but It is necessary to make the code refactoring to get variables from autogen process.
